blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/ahmadreza-log/daily-dev-jokes/discussions
    about: ğŸ’­ Got questions? Want to chat? Join our discussions and let's talk about all things dev jokes! ğŸ‰

